-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is `Puppy.Deps.Nothing`: an entry point
-- taking an array reaches it by running off the end, and one pulling its
-- tokens by asking for another and being told there are none. Either way no
-- caller can write one in the middle of the input and have the rest of it
-- silently ignored.
module Puppy.Fixture.Offside.Block
  ( expression
  , expressionFrom
  ) where

import Prelude

import Puppy.Runtime as Puppy.Runtime
import Puppy.Runtime.Deps as Puppy.Deps

import Puppy.Fixture.Offside.Token as T

-- | Which terminal a token is.
-- |
-- | The `Boolean` is always `true`. It is there so that the last arm below
-- | cannot be proved unreachable, whatever the patterns above it cover
-- | between them -- while leaving those patterns checked against one
-- | another, so that a pattern written where a narrower one should have come
-- | first is still reported.
puppyIndexOf :: Boolean -> Puppy.Deps.Maybe (T.Token) -> Int
puppyIndexOf = case _, _ of
  true, Puppy.Deps.Just (T.At _ T.Let) -> 0
  true, Puppy.Deps.Just (T.At _ T.In) -> 1
  true, Puppy.Deps.Just (T.At _ T.Equals) -> 2
  true, Puppy.Deps.Just (T.At _ T.Plus) -> 3
  true, Puppy.Deps.Just (T.At _ (T.Name _)) -> 4
  true, Puppy.Deps.Just (T.At _ (T.Number _)) -> 5
  true, Puppy.Deps.Just (T.At _ T.BlockStart) -> 6
  true, Puppy.Deps.Just (T.At _ T.BlockSep) -> 7
  true, Puppy.Deps.Just (T.At _ T.BlockEnd) -> 8
  true, Puppy.Deps.Nothing -> 9
  _, _ -> 10

terminalIndex :: Puppy.Deps.Maybe (T.Token) -> Int
terminalIndex = puppyIndexOf true

-- | The value a token carries, boxed for the parser stack. The `Boolean` is
-- | there for the reason given above.
puppyValueOf :: Boolean -> Puppy.Deps.Maybe (T.Token) -> Puppy.Runtime.Value
puppyValueOf = case _, _ of
  true, Puppy.Deps.Just (T.At _ T.Let) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ T.In) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ T.Equals) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ T.Plus) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ (T.Name puppyPayload)) -> Puppy.Runtime.box puppyPayload
  true, Puppy.Deps.Just (T.At _ (T.Number puppyPayload)) -> Puppy.Runtime.box puppyPayload
  true, Puppy.Deps.Just (T.At _ T.BlockStart) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ T.BlockSep) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Just (T.At _ T.BlockEnd) -> Puppy.Runtime.box unit
  true, Puppy.Deps.Nothing -> Puppy.Runtime.box unit
  _, _ -> Puppy.Runtime.internalError
    "a value was asked for a token this grammar does not declare"

terminalValue :: Puppy.Deps.Maybe (T.Token) -> Puppy.Runtime.Value
terminalValue = puppyValueOf true

terminalNames :: Array String
terminalNames =
  [ "let"
  , "in"
  , "="
  , "+"
  , "a name"
  , "a number"
  , "the start of a block"
  , "the start of a declaration"
  , "the end of a block"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Puppy.Deps.index terminalNames puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Puppy.Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "expression -> expr" }
  , { lhs: 1, arity: 6, name: "expr -> LET VOPEN decls VCLOSE IN expr" }
  , { lhs: 1, arity: 1, name: "expr -> sum" }
  , { lhs: 2, arity: 1, name: "decls -> decl" }
  , { lhs: 2, arity: 3, name: "decls -> decl VSEP decls" }
  , { lhs: 4, arity: 3, name: "decl -> NAME EQUALS expr" }
  , { lhs: 3, arity: 3, name: "sum -> sum PLUS atom" }
  , { lhs: 3, arity: 1, name: "sum -> atom" }
  , { lhs: 5, arity: 1, name: "atom -> NAME" }
  , { lhs: 5, arity: 1, name: "atom -> NUMBER" }
  , { lhs: 6, arity: 1, name: "<start expression> -> expression" }
  ]

productionAt :: Int -> Puppy.Runtime.ProductionInfo
productionAt puppyIndex = case Puppy.Deps.index productionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Puppy.Runtime.Value -> Puppy.Runtime.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        e :: String
        e = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((e) :: String)
  , \puppyValues ->
      let
        ds :: String
        ds = Puppy.Runtime.unbox (Puppy.Runtime.slot 2 puppyValues)

        e :: String
        e = Puppy.Runtime.unbox (Puppy.Runtime.slot 5 puppyValues)
      in
        Puppy.Runtime.box
          (("(let " <> ds <> " in " <> e <> ")") :: String)
  , \puppyValues ->
      let
        s :: String
        s = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((s) :: String)
  , \puppyValues ->
      let
        d :: String
        d = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((d) :: String)
  , \puppyValues ->
      let
        d :: String
        d = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)

        ds :: String
        ds = Puppy.Runtime.unbox (Puppy.Runtime.slot 2 puppyValues)
      in
        Puppy.Runtime.box
          ((d <> " " <> ds) :: String)
  , \puppyValues ->
      let
        n :: String
        n = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)

        e :: String
        e = Puppy.Runtime.unbox (Puppy.Runtime.slot 2 puppyValues)
      in
        Puppy.Runtime.box
          ((n <> "=" <> e) :: String)
  , \puppyValues ->
      let
        a :: String
        a = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)

        b :: String
        b = Puppy.Runtime.unbox (Puppy.Runtime.slot 2 puppyValues)
      in
        Puppy.Runtime.box
          (("(" <> a <> "+" <> b <> ")") :: String)
  , \puppyValues ->
      let
        a :: String
        a = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((a) :: String)
  , \puppyValues ->
      let
        n :: String
        n = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((n) :: String)
  , \puppyValues ->
      let
        i :: Int
        i = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((show i) :: String)
  , \_ -> Puppy.Runtime.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Puppy.Runtime.Value -> Puppy.Runtime.Value
semanticActionAt puppyIndex = case Puppy.Deps.index semanticActionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no semantic action " <> show puppyIndex)

actionRows :: Array (Array { on :: Int, take :: Puppy.Runtime.Action })
actionRows =
  [ [ { on: 0, take: Puppy.Runtime.Shift 1 }, { on: 4, take: Puppy.Runtime.Shift 2 }, { on: 5, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 6, take: Puppy.Runtime.Shift 10 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 8 }, { on: 7, take: Puppy.Runtime.Reduce 8 }, { on: 8, take: Puppy.Runtime.Reduce 8 }, { on: 9, take: Puppy.Runtime.Reduce 8 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 9 }, { on: 7, take: Puppy.Runtime.Reduce 9 }, { on: 8, take: Puppy.Runtime.Reduce 9 }, { on: 9, take: Puppy.Runtime.Reduce 9 } ]
  , [ { on: 9, take: Puppy.Runtime.Accept } ]
  , [ { on: 9, take: Puppy.Runtime.Reduce 0 } ]
  , [ { on: 3, take: Puppy.Runtime.Shift 8 }, { on: 7, take: Puppy.Runtime.Reduce 2 }, { on: 8, take: Puppy.Runtime.Reduce 2 }, { on: 9, take: Puppy.Runtime.Reduce 2 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 7 }, { on: 7, take: Puppy.Runtime.Reduce 7 }, { on: 8, take: Puppy.Runtime.Reduce 7 }, { on: 9, take: Puppy.Runtime.Reduce 7 } ]
  , [ { on: 4, take: Puppy.Runtime.Shift 2 }, { on: 5, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 6 }, { on: 7, take: Puppy.Runtime.Reduce 6 }, { on: 8, take: Puppy.Runtime.Reduce 6 }, { on: 9, take: Puppy.Runtime.Reduce 6 } ]
  , [ { on: 4, take: Puppy.Runtime.Shift 11 } ]
  , [ { on: 2, take: Puppy.Runtime.Shift 19 } ]
  , [ { on: 8, take: Puppy.Runtime.Shift 16 } ]
  , [ { on: 7, take: Puppy.Runtime.Shift 14 }, { on: 8, take: Puppy.Runtime.Reduce 3 } ]
  , [ { on: 4, take: Puppy.Runtime.Shift 11 } ]
  , [ { on: 8, take: Puppy.Runtime.Reduce 4 } ]
  , [ { on: 1, take: Puppy.Runtime.Shift 17 } ]
  , [ { on: 0, take: Puppy.Runtime.Shift 1 }, { on: 4, take: Puppy.Runtime.Shift 2 }, { on: 5, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 7, take: Puppy.Runtime.Reduce 1 }, { on: 8, take: Puppy.Runtime.Reduce 1 }, { on: 9, take: Puppy.Runtime.Reduce 1 } ]
  , [ { on: 0, take: Puppy.Runtime.Shift 1 }, { on: 4, take: Puppy.Runtime.Shift 2 }, { on: 5, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 7, take: Puppy.Runtime.Reduce 5 }, { on: 8, take: Puppy.Runtime.Reduce 5 } ]
  ]

actionAt :: Int -> Int -> Puppy.Runtime.Action
actionAt puppyState puppyTerminal = case Puppy.Deps.index actionRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no action row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.take
    Puppy.Deps.Nothing -> Puppy.Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 4 }, { on: 1, to: 5 }, { on: 3, to: 6 }, { on: 5, to: 7 } ]
  , []
  , []
  , []
  , []
  , []
  , []
  , []
  , [ { on: 5, to: 9 } ]
  , []
  , [ { on: 2, to: 12 }, { on: 4, to: 13 } ]
  , []
  , []
  , []
  , [ { on: 2, to: 15 }, { on: 4, to: 13 } ]
  , []
  , []
  , [ { on: 1, to: 18 }, { on: 3, to: 6 }, { on: 5, to: 7 } ]
  , []
  , [ { on: 1, to: 20 }, { on: 3, to: 6 }, { on: 5, to: 7 } ]
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Puppy.Deps.index gotoRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no goto row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.to
    Puppy.Deps.Nothing -> Puppy.Runtime.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Puppy.Runtime.Table (Puppy.Deps.Maybe (T.Token)) Puppy.Runtime.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 10
  , startState: puppyStart
  }

-- | End of input is `Puppy.Deps.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Puppy.Runtime.ParseError (Puppy.Deps.Maybe (T.Token))
  -> Puppy.Runtime.ParseError (T.Token)
toParseError puppyError =
  puppyError { found = Puppy.Deps.fromMaybe Puppy.Deps.Nothing puppyError.found }

fromResult
  :: forall puppyResult
   . Puppy.Deps.Either (Puppy.Runtime.ParseError (Puppy.Deps.Maybe (T.Token))) Puppy.Runtime.Value
  -> Puppy.Deps.Either (Puppy.Runtime.ParseError (T.Token)) puppyResult
fromResult = case _ of
  Puppy.Deps.Left puppyError -> Puppy.Deps.Left (toParseError puppyError)
  Puppy.Deps.Right puppyValue -> Puppy.Deps.Right (Puppy.Runtime.unbox puppyValue)

-- | Feed the parser from an array, without building a second one.
-- |
-- | The driver reads a `Puppy.Deps.Maybe` of the token type, and that is
-- | exactly what a lookup past the end of an array answers, so the same
-- | `Puppy.Deps.index` both reads a token and says there are no more.
runArray
  :: Array (T.Token)
  -> Int
  -> Puppy.Runtime.Step (Puppy.Deps.Maybe (T.Token)) Puppy.Runtime.Value
  -> Puppy.Deps.Either (Puppy.Runtime.ParseError (Puppy.Deps.Maybe (T.Token))) Puppy.Runtime.Value
runArray puppyInput puppyIndex puppyStep = case puppyStep of
  Puppy.Runtime.Await puppyResume ->
    runArray puppyInput (puppyIndex + 1)
      (Puppy.Runtime.resume puppyResume (Puppy.Deps.index puppyInput puppyIndex))
  Puppy.Runtime.Done puppyValue -> Puppy.Deps.Right puppyValue
  Puppy.Runtime.Failed puppyError -> Puppy.Deps.Left puppyError

expression :: Array (T.Token) -> Puppy.Deps.Either (Puppy.Runtime.ParseError (T.Token)) (String)
expression puppyInput =
  fromResult (runArray puppyInput 0 (Puppy.Runtime.start (tableFor 0)))

expressionFrom
  :: forall m
   . Puppy.Deps.MonadRec m
  => m (Puppy.Deps.Maybe (T.Token))
  -> m (Puppy.Deps.Either (Puppy.Runtime.ParseError (T.Token)) (String))
expressionFrom puppyNext =
  map fromResult (Puppy.Runtime.parseM (tableFor 0) puppyNext)
