-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is the `Puppy.Deps.Nothing` the entry points
-- below append, which is why no caller can write one in the middle of the
-- input and have the rest of it silently ignored.
module Puppy.Fixture.Awkward
  ( Token(..)
  , input
  , state
  ) where

import Prelude

import Puppy.Runtime as Puppy.Runtime
import Puppy.Runtime.Deps as Puppy.Deps

data Token
  = STATE
  | VALUE (Int)
  | TAB
  | CTRL

derive instance Eq Token

instance Show Token where
  show = case _ of
    STATE -> "STATE"
    VALUE puppyPayload -> "(VALUE " <> show puppyPayload <> ")"
    TAB -> "TAB"
    CTRL -> "CTRL"

terminalIndex :: Puppy.Deps.Maybe Token -> Int
terminalIndex = case _ of
  Puppy.Deps.Just STATE -> 0
  Puppy.Deps.Just (VALUE _) -> 1
  Puppy.Deps.Just TAB -> 2
  Puppy.Deps.Just CTRL -> 3
  Puppy.Deps.Nothing -> 4

terminalValue :: Puppy.Deps.Maybe Token -> Puppy.Runtime.Value
terminalValue = case _ of
  Puppy.Deps.Just STATE -> Puppy.Runtime.box unit
  Puppy.Deps.Just (VALUE puppyPayload) -> Puppy.Runtime.box puppyPayload
  Puppy.Deps.Just TAB -> Puppy.Runtime.box unit
  Puppy.Deps.Just CTRL -> Puppy.Runtime.box unit
  Puppy.Deps.Nothing -> Puppy.Runtime.box unit

terminalNames :: Array String
terminalNames =
  [ "STATE"
  , "VALUE"
  , "a\tb"
  , "x\x01" <> "Ay"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Puppy.Deps.index terminalNames puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Puppy.Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "input -> value" }
  , { lhs: 1, arity: 1, name: "value -> VALUE" }
  , { lhs: 1, arity: 1, name: "value -> STATE" }
  , { lhs: 1, arity: 1, name: "value -> TAB" }
  , { lhs: 1, arity: 1, name: "value -> CTRL" }
  , { lhs: 2, arity: 1, name: "state -> value" }
  , { lhs: 3, arity: 1, name: "<start input> -> input" }
  , { lhs: 4, arity: 1, name: "<start state> -> state" }
  ]

productionAt :: Int -> Puppy.Runtime.ProductionInfo
productionAt puppyIndex = case Puppy.Deps.index productionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Puppy.Runtime.Value -> Puppy.Runtime.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        row :: Int
        row = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((row) :: Int)
  , \puppyValues ->
      let
        entry :: Int
        entry = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((entry) :: Int)
  , \_ ->
      Puppy.Runtime.box
        ((0) :: Int)
  , \_ ->
      Puppy.Runtime.box
        ((1) :: Int)
  , \_ ->
      Puppy.Runtime.box
        ((2) :: Int)
  , \puppyValues ->
      let
        err :: Int
        err = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((err) :: Int)
  , \_ -> Puppy.Runtime.internalError
      "the start production has no semantic action"
  , \_ -> Puppy.Runtime.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Puppy.Runtime.Value -> Puppy.Runtime.Value
semanticActionAt puppyIndex = case Puppy.Deps.index semanticActionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no semantic action " <> show puppyIndex)

actionRows :: Array (Array { on :: Int, take :: Puppy.Runtime.Action })
actionRows =
  [ [ { on: 0, take: Puppy.Runtime.Shift 2 }, { on: 1, take: Puppy.Runtime.Shift 3 }, { on: 2, take: Puppy.Runtime.Shift 4 }, { on: 3, take: Puppy.Runtime.Shift 5 } ]
  , [ { on: 0, take: Puppy.Runtime.Shift 2 }, { on: 1, take: Puppy.Runtime.Shift 3 }, { on: 2, take: Puppy.Runtime.Shift 4 }, { on: 3, take: Puppy.Runtime.Shift 5 } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 2 } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 1 } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 3 } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 4 } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 5 } ]
  , [ { on: 4, take: Puppy.Runtime.Accept } ]
  , [ { on: 4, take: Puppy.Runtime.Accept } ]
  , [ { on: 4, take: Puppy.Runtime.Reduce 0 } ]
  ]

actionAt :: Int -> Int -> Puppy.Runtime.Action
actionAt puppyState puppyTerminal = case Puppy.Deps.index actionRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no action row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.take
    Puppy.Deps.Nothing -> Puppy.Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 8 }, { on: 1, to: 9 } ]
  , [ { on: 1, to: 6 }, { on: 2, to: 7 } ]
  , []
  , []
  , []
  , []
  , []
  , []
  , []
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Puppy.Deps.index gotoRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no goto row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.to
    Puppy.Deps.Nothing -> Puppy.Runtime.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Puppy.Runtime.Table (Puppy.Deps.Maybe Token) Puppy.Runtime.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 5
  , startState: puppyStart
  }

feed :: Array Token -> Array (Puppy.Deps.Maybe Token)
feed puppyInput = Puppy.Deps.snoc (map Puppy.Deps.Just puppyInput) Puppy.Deps.Nothing

-- | End of input is `Puppy.Deps.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Puppy.Runtime.ParseError (Puppy.Deps.Maybe Token)
  -> Puppy.Runtime.ParseError Token
toParseError puppyError =
  puppyError { found = Puppy.Deps.fromMaybe Puppy.Deps.Nothing puppyError.found }

input :: Array Token -> Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (Int)
input puppyInput =
  case Puppy.Runtime.parse (tableFor 0) (feed puppyInput) of
    Puppy.Deps.Left puppyError -> Puppy.Deps.Left (toParseError puppyError)
    Puppy.Deps.Right puppyValue -> Puppy.Deps.Right (Puppy.Runtime.unbox puppyValue)

state :: Array Token -> Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (Int)
state puppyInput =
  case Puppy.Runtime.parse (tableFor 1) (feed puppyInput) of
    Puppy.Deps.Left puppyError -> Puppy.Deps.Left (toParseError puppyError)
    Puppy.Deps.Right puppyValue -> Puppy.Deps.Right (Puppy.Runtime.unbox puppyValue)
