-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is the `Maybe.Nothing` the entry points
-- below append, which is why no caller can write one in the middle of the
-- input and have the rest of it silently ignored.
module Puppy.Fixture.Awkward
  ( Token(..)
  , input
  , state
  ) where

import Prelude

import Data.Array as Array
import Data.Either as Either
import Data.Maybe as Maybe
import Puppy.Runtime as Runtime
import Puppy.Runtime.Value as Value

data Token
  = STATE
  | VALUE (Int)
  | TAB
  | CTRL

derive instance Eq Token

instance Show Token where
  show = case _ of
    STATE -> "STATE"
    VALUE puppyPayload -> "(VALUE " <> show puppyPayload <> ")"
    TAB -> "TAB"
    CTRL -> "CTRL"

terminalIndex :: Maybe.Maybe Token -> Int
terminalIndex = case _ of
  Maybe.Just STATE -> 0
  Maybe.Just (VALUE _) -> 1
  Maybe.Just TAB -> 2
  Maybe.Just CTRL -> 3
  Maybe.Nothing -> 4

terminalValue :: Maybe.Maybe Token -> Value.Value
terminalValue = case _ of
  Maybe.Just STATE -> Value.box unit
  Maybe.Just (VALUE puppyPayload) -> Value.box puppyPayload
  Maybe.Just TAB -> Value.box unit
  Maybe.Just CTRL -> Value.box unit
  Maybe.Nothing -> Value.box unit

terminalNames :: Array String
terminalNames =
  [ "STATE"
  , "VALUE"
  , "a\tb"
  , "x\x01" <> "Ay"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Array.index terminalNames puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Value.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "input -> value" }
  , { lhs: 1, arity: 1, name: "value -> VALUE" }
  , { lhs: 1, arity: 1, name: "value -> STATE" }
  , { lhs: 1, arity: 1, name: "value -> TAB" }
  , { lhs: 1, arity: 1, name: "value -> CTRL" }
  , { lhs: 2, arity: 1, name: "state -> value" }
  , { lhs: 3, arity: 1, name: "<start input> -> input" }
  , { lhs: 4, arity: 1, name: "<start state> -> state" }
  ]

productionAt :: Int -> Runtime.ProductionInfo
productionAt puppyIndex = case Array.index productionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Value.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Value.Value -> Value.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        row :: Int
        row = Value.unbox (Value.slot 0 puppyValues)
      in
        Value.box
          ((row) :: Int)
  , \puppyValues ->
      let
        entry :: Int
        entry = Value.unbox (Value.slot 0 puppyValues)
      in
        Value.box
          ((entry) :: Int)
  , \_ ->
      Value.box
        ((0) :: Int)
  , \_ ->
      Value.box
        ((1) :: Int)
  , \_ ->
      Value.box
        ((2) :: Int)
  , \puppyValues ->
      let
        err :: Int
        err = Value.unbox (Value.slot 0 puppyValues)
      in
        Value.box
          ((err) :: Int)
  , \_ -> Value.internalError
      "the start production has no semantic action"
  , \_ -> Value.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Value.Value -> Value.Value
semanticActionAt puppyIndex = case Array.index semanticActionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Value.internalError
    ("no semantic action " <> show puppyIndex)

actionRows :: Array (Array { on :: Int, take :: Runtime.Action })
actionRows =
  [ [ { on: 0, take: Runtime.Shift 2 }, { on: 1, take: Runtime.Shift 3 }, { on: 2, take: Runtime.Shift 4 }, { on: 3, take: Runtime.Shift 5 } ]
  , [ { on: 0, take: Runtime.Shift 2 }, { on: 1, take: Runtime.Shift 3 }, { on: 2, take: Runtime.Shift 4 }, { on: 3, take: Runtime.Shift 5 } ]
  , [ { on: 4, take: Runtime.Reduce 2 } ]
  , [ { on: 4, take: Runtime.Reduce 1 } ]
  , [ { on: 4, take: Runtime.Reduce 3 } ]
  , [ { on: 4, take: Runtime.Reduce 4 } ]
  , [ { on: 4, take: Runtime.Reduce 5 } ]
  , [ { on: 4, take: Runtime.Accept } ]
  , [ { on: 4, take: Runtime.Accept } ]
  , [ { on: 4, take: Runtime.Reduce 0 } ]
  ]

actionAt :: Int -> Int -> Runtime.Action
actionAt puppyState puppyTerminal = case Array.index actionRows puppyState of
  Maybe.Nothing -> Value.internalError
    ("no action row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.take
    Maybe.Nothing -> Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 8 }, { on: 1, to: 9 } ]
  , [ { on: 1, to: 6 }, { on: 2, to: 7 } ]
  , []
  , []
  , []
  , []
  , []
  , []
  , []
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Array.index gotoRows puppyState of
  Maybe.Nothing -> Value.internalError
    ("no goto row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.to
    Maybe.Nothing -> Value.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Runtime.Table (Maybe.Maybe Token) Value.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 5
  , startState: puppyStart
  }

feed :: Array Token -> Array (Maybe.Maybe Token)
feed puppyInput = Array.snoc (map Maybe.Just puppyInput) Maybe.Nothing

-- | End of input is `Maybe.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Runtime.ParseError (Maybe.Maybe Token)
  -> Runtime.ParseError Token
toParseError puppyError =
  puppyError { found = Maybe.fromMaybe Maybe.Nothing puppyError.found }

input :: Array Token -> Either.Either (Runtime.ParseError Token) (Int)
input puppyInput =
  case Runtime.parse (tableFor 0) (feed puppyInput) of
    Either.Left puppyError -> Either.Left (toParseError puppyError)
    Either.Right puppyValue -> Either.Right (Value.unbox puppyValue)

state :: Array Token -> Either.Either (Runtime.ParseError Token) (Int)
state puppyInput =
  case Runtime.parse (tableFor 1) (feed puppyInput) of
    Either.Left puppyError -> Either.Left (toParseError puppyError)
    Either.Right puppyValue -> Either.Right (Value.unbox puppyValue)
