-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is the `Maybe.Nothing` the entry points
-- below append, which is why no caller can write one in the middle of the
-- input and have the rest of it silently ignored.
module Puppy.Fixture.Calculator
  ( Token(..)
  , expression
  ) where

import Prelude

import Data.Array as Array
import Data.Either as Either
import Data.Maybe as Maybe
import Puppy.Runtime as Runtime

data Token
  = PLUS
  | TIMES
  | LPAREN
  | RPAREN
  | INT (Int)

derive instance Eq Token

instance Show Token where
  show = case _ of
    PLUS -> "PLUS"
    TIMES -> "TIMES"
    LPAREN -> "LPAREN"
    RPAREN -> "RPAREN"
    INT puppyPayload -> "(INT " <> show puppyPayload <> ")"

terminalIndex :: Maybe.Maybe Token -> Int
terminalIndex = case _ of
  Maybe.Just PLUS -> 0
  Maybe.Just TIMES -> 1
  Maybe.Just LPAREN -> 2
  Maybe.Just RPAREN -> 3
  Maybe.Just (INT _) -> 4
  Maybe.Nothing -> 5

terminalValue :: Maybe.Maybe Token -> Runtime.Value
terminalValue = case _ of
  Maybe.Just PLUS -> Runtime.box unit
  Maybe.Just TIMES -> Runtime.box unit
  Maybe.Just LPAREN -> Runtime.box unit
  Maybe.Just RPAREN -> Runtime.box unit
  Maybe.Just (INT puppyPayload) -> Runtime.box puppyPayload
  Maybe.Nothing -> Runtime.box unit

terminalNames :: Array String
terminalNames =
  [ "PLUS"
  , "TIMES"
  , "LPAREN"
  , "RPAREN"
  , "INT"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Array.index terminalNames puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "expression -> expr" }
  , { lhs: 1, arity: 1, name: "expr -> INT" }
  , { lhs: 1, arity: 3, name: "expr -> expr PLUS expr" }
  , { lhs: 1, arity: 3, name: "expr -> expr TIMES expr" }
  , { lhs: 1, arity: 3, name: "expr -> LPAREN expr RPAREN" }
  , { lhs: 2, arity: 1, name: "<start expression> -> expression" }
  ]

productionAt :: Int -> Runtime.ProductionInfo
productionAt puppyIndex = case Array.index productionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Runtime.Value -> Runtime.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        e :: Int
        e = Runtime.unbox (Runtime.slot 0 puppyValues)
      in
        Runtime.box
          ((e) :: Int)
  , \puppyValues ->
      let
        i :: Int
        i = Runtime.unbox (Runtime.slot 0 puppyValues)
      in
        Runtime.box
          ((i) :: Int)
  , \puppyValues ->
      let
        a :: Int
        a = Runtime.unbox (Runtime.slot 0 puppyValues)

        b :: Int
        b = Runtime.unbox (Runtime.slot 2 puppyValues)
      in
        Runtime.box
          ((a + b) :: Int)
  , \puppyValues ->
      let
        a :: Int
        a = Runtime.unbox (Runtime.slot 0 puppyValues)

        b :: Int
        b = Runtime.unbox (Runtime.slot 2 puppyValues)
      in
        Runtime.box
          ((a * b) :: Int)
  , \puppyValues ->
      let
        e :: Int
        e = Runtime.unbox (Runtime.slot 1 puppyValues)
      in
        Runtime.box
          ((e) :: Int)
  , \_ -> Runtime.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Runtime.Value -> Runtime.Value
semanticActionAt puppyIndex = case Array.index semanticActionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no semantic action " <> show puppyIndex)

actionRows :: Array (Array { on :: Int, take :: Runtime.Action })
actionRows =
  [ [ { on: 2, take: Runtime.Shift 1 }, { on: 4, take: Runtime.Shift 2 } ]
  , [ { on: 2, take: Runtime.Shift 1 }, { on: 4, take: Runtime.Shift 2 } ]
  , [ { on: 0, take: Runtime.Reduce 1 }, { on: 1, take: Runtime.Reduce 1 }, { on: 3, take: Runtime.Reduce 1 }, { on: 5, take: Runtime.Reduce 1 } ]
  , [ { on: 5, take: Runtime.Accept } ]
  , [ { on: 0, take: Runtime.Shift 5 }, { on: 1, take: Runtime.Shift 6 }, { on: 5, take: Runtime.Reduce 0 } ]
  , [ { on: 2, take: Runtime.Shift 1 }, { on: 4, take: Runtime.Shift 2 } ]
  , [ { on: 2, take: Runtime.Shift 1 }, { on: 4, take: Runtime.Shift 2 } ]
  , [ { on: 0, take: Runtime.Reduce 3 }, { on: 1, take: Runtime.Reduce 3 }, { on: 3, take: Runtime.Reduce 3 }, { on: 5, take: Runtime.Reduce 3 } ]
  , [ { on: 0, take: Runtime.Reduce 2 }, { on: 1, take: Runtime.Shift 6 }, { on: 3, take: Runtime.Reduce 2 }, { on: 5, take: Runtime.Reduce 2 } ]
  , [ { on: 0, take: Runtime.Shift 5 }, { on: 1, take: Runtime.Shift 6 }, { on: 3, take: Runtime.Shift 10 } ]
  , [ { on: 0, take: Runtime.Reduce 4 }, { on: 1, take: Runtime.Reduce 4 }, { on: 3, take: Runtime.Reduce 4 }, { on: 5, take: Runtime.Reduce 4 } ]
  ]

actionAt :: Int -> Int -> Runtime.Action
actionAt puppyState puppyTerminal = case Array.index actionRows puppyState of
  Maybe.Nothing -> Runtime.internalError
    ("no action row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.take
    Maybe.Nothing -> Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 3 }, { on: 1, to: 4 } ]
  , [ { on: 1, to: 9 } ]
  , []
  , []
  , []
  , [ { on: 1, to: 8 } ]
  , [ { on: 1, to: 7 } ]
  , []
  , []
  , []
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Array.index gotoRows puppyState of
  Maybe.Nothing -> Runtime.internalError
    ("no goto row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.to
    Maybe.Nothing -> Runtime.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Runtime.Table (Maybe.Maybe Token) Runtime.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 6
  , startState: puppyStart
  }

feed :: Array Token -> Array (Maybe.Maybe Token)
feed puppyInput = Array.snoc (map Maybe.Just puppyInput) Maybe.Nothing

-- | End of input is `Maybe.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Runtime.ParseError (Maybe.Maybe Token)
  -> Runtime.ParseError Token
toParseError puppyError =
  puppyError { found = Maybe.fromMaybe Maybe.Nothing puppyError.found }

expression :: Array Token -> Either.Either (Runtime.ParseError Token) (Int)
expression puppyInput =
  case Runtime.parse (tableFor 0) (feed puppyInput) of
    Either.Left puppyError -> Either.Left (toParseError puppyError)
    Either.Right puppyValue -> Either.Right (Runtime.unbox puppyValue)
