-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is the `Maybe.Nothing` the entry points
-- below append, which is why no caller can write one in the middle of the
-- input and have the rest of it silently ignored.
module Puppy.Fixture.Lists
  ( Token(..)
  , items
  , single
  ) where

import Prelude

import Data.Array as Array
import Data.Either as Either
import Data.Maybe as Maybe
import Puppy.Runtime as Runtime

data Token
  = COMMA
  | A (String)
  | B (String)

derive instance Eq Token

instance Show Token where
  show = case _ of
    COMMA -> "COMMA"
    A puppyPayload -> "(A " <> show puppyPayload <> ")"
    B puppyPayload -> "(B " <> show puppyPayload <> ")"

terminalIndex :: Maybe.Maybe Token -> Int
terminalIndex = case _ of
  Maybe.Just COMMA -> 0
  Maybe.Just (A _) -> 1
  Maybe.Just (B _) -> 2
  Maybe.Nothing -> 3

terminalValue :: Maybe.Maybe Token -> Runtime.Value
terminalValue = case _ of
  Maybe.Just COMMA -> Runtime.box unit
  Maybe.Just (A puppyPayload) -> Runtime.box puppyPayload
  Maybe.Just (B puppyPayload) -> Runtime.box puppyPayload
  Maybe.Nothing -> Runtime.box unit

terminalNames :: Array String
terminalNames =
  [ "COMMA"
  , "A"
  , "B"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Array.index terminalNames puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "items -> list" }
  , { lhs: 1, arity: 0, name: "list -> <empty>" }
  , { lhs: 1, arity: 2, name: "list -> item tail" }
  , { lhs: 2, arity: 1, name: "item -> A" }
  , { lhs: 2, arity: 1, name: "item -> B" }
  , { lhs: 3, arity: 0, name: "tail -> <empty>" }
  , { lhs: 3, arity: 3, name: "tail -> COMMA item tail" }
  , { lhs: 4, arity: 1, name: "single -> item" }
  , { lhs: 5, arity: 1, name: "<start items> -> items" }
  , { lhs: 6, arity: 1, name: "<start single> -> single" }
  ]

productionAt :: Int -> Runtime.ProductionInfo
productionAt puppyIndex = case Array.index productionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Runtime.Value -> Runtime.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        xs :: Array String
        xs = Runtime.unbox (Runtime.slot 0 puppyValues)
      in
        Runtime.box
          ((xs) :: Array String)
  , \_ ->
      Runtime.box
        (([]) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Runtime.unbox (Runtime.slot 0 puppyValues)

        rest :: Array String
        rest = Runtime.unbox (Runtime.slot 1 puppyValues)
      in
        Runtime.box
          (([ x ] <> rest) :: Array String)
  , \puppyValues ->
      let
        x = Runtime.unbox (puppyInline3_0 puppyValues)
      in
        Runtime.box
          (("[" <> x <> "]") :: String)
  , \puppyValues ->
      let
        x = Runtime.unbox (puppyInline4_0 puppyValues)
      in
        Runtime.box
          (("[" <> x <> "]") :: String)
  , \_ ->
      Runtime.box
        (([]) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Runtime.unbox (Runtime.slot 1 puppyValues)

        rest :: Array String
        rest = Runtime.unbox (Runtime.slot 2 puppyValues)
      in
        Runtime.box
          (([ x ] <> rest) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Runtime.unbox (Runtime.slot 0 puppyValues)
      in
        Runtime.box
          ((x) :: String)
  , \_ -> Runtime.internalError
      "the start production has no semantic action"
  , \_ -> Runtime.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Runtime.Value -> Runtime.Value
semanticActionAt puppyIndex = case Array.index semanticActionTable puppyIndex of
  Maybe.Just puppyFound -> puppyFound
  Maybe.Nothing -> Runtime.internalError
    ("no semantic action " <> show puppyIndex)

puppyInline3_0 :: Array Runtime.Value -> Runtime.Value
puppyInline3_0 puppyValues =
  let
    x :: String
    x = Runtime.unbox (Runtime.slot 0 puppyValues)
  in
    Runtime.box
      (x <> "!")

puppyInline4_0 :: Array Runtime.Value -> Runtime.Value
puppyInline4_0 puppyValues =
  let
    x :: String
    x = Runtime.unbox (Runtime.slot 0 puppyValues)
  in
    Runtime.box
      (x <> "?")

actionRows :: Array (Array { on :: Int, take :: Runtime.Action })
actionRows =
  [ [ { on: 1, take: Runtime.Shift 2 }, { on: 2, take: Runtime.Shift 3 }, { on: 3, take: Runtime.Reduce 1 } ]
  , [ { on: 1, take: Runtime.Shift 2 }, { on: 2, take: Runtime.Shift 3 } ]
  , [ { on: 0, take: Runtime.Reduce 3 }, { on: 3, take: Runtime.Reduce 3 } ]
  , [ { on: 0, take: Runtime.Reduce 4 }, { on: 3, take: Runtime.Reduce 4 } ]
  , [ { on: 3, take: Runtime.Reduce 7 } ]
  , [ { on: 3, take: Runtime.Accept } ]
  , [ { on: 3, take: Runtime.Accept } ]
  , [ { on: 3, take: Runtime.Reduce 0 } ]
  , [ { on: 0, take: Runtime.Shift 9 }, { on: 3, take: Runtime.Reduce 5 } ]
  , [ { on: 1, take: Runtime.Shift 2 }, { on: 2, take: Runtime.Shift 3 } ]
  , [ { on: 3, take: Runtime.Reduce 2 } ]
  , [ { on: 0, take: Runtime.Shift 9 }, { on: 3, take: Runtime.Reduce 5 } ]
  , [ { on: 3, take: Runtime.Reduce 6 } ]
  ]

actionAt :: Int -> Int -> Runtime.Action
actionAt puppyState puppyTerminal = case Array.index actionRows puppyState of
  Maybe.Nothing -> Runtime.internalError
    ("no action row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.take
    Maybe.Nothing -> Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 6 }, { on: 1, to: 7 }, { on: 2, to: 8 } ]
  , [ { on: 2, to: 4 }, { on: 4, to: 5 } ]
  , []
  , []
  , []
  , []
  , []
  , []
  , [ { on: 3, to: 10 } ]
  , [ { on: 2, to: 11 } ]
  , []
  , [ { on: 3, to: 12 } ]
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Array.index gotoRows puppyState of
  Maybe.Nothing -> Runtime.internalError
    ("no goto row for state " <> show puppyState)
  Maybe.Just puppyRow -> case Array.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Maybe.Just puppyEntry -> puppyEntry.to
    Maybe.Nothing -> Runtime.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Runtime.Table (Maybe.Maybe Token) Runtime.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 4
  , startState: puppyStart
  }

feed :: Array Token -> Array (Maybe.Maybe Token)
feed puppyInput = Array.snoc (map Maybe.Just puppyInput) Maybe.Nothing

-- | End of input is `Maybe.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Runtime.ParseError (Maybe.Maybe Token)
  -> Runtime.ParseError Token
toParseError puppyError =
  puppyError { found = Maybe.fromMaybe Maybe.Nothing puppyError.found }

items :: Array Token -> Either.Either (Runtime.ParseError Token) (Array String)
items puppyInput =
  case Runtime.parse (tableFor 0) (feed puppyInput) of
    Either.Left puppyError -> Either.Left (toParseError puppyError)
    Either.Right puppyValue -> Either.Right (Runtime.unbox puppyValue)

single :: Array Token -> Either.Either (Runtime.ParseError Token) (String)
single puppyInput =
  case Runtime.parse (tableFor 1) (feed puppyInput) of
    Either.Left puppyError -> Either.Left (toParseError puppyError)
    Either.Right puppyValue -> Either.Right (Runtime.unbox puppyValue)
