-- Generated by Puppy. Do not edit.
--
-- End of input is not a token. It is `Puppy.Deps.Nothing`: an entry point
-- taking an array reaches it by running off the end, and one pulling its
-- tokens by asking for another and being told there are none. Either way no
-- caller can write one in the middle of the input and have the rest of it
-- silently ignored.
module Puppy.Fixture.Lists
  ( Token(..)
  , items
  , itemsFrom
  , single
  , singleFrom
  ) where

import Prelude

import Puppy.Runtime as Puppy.Runtime
import Puppy.Runtime.Deps as Puppy.Deps

data Token
  = COMMA
  | A (String)
  | B (String)

derive instance Eq Token

instance Show Token where
  show = case _ of
    COMMA -> "COMMA"
    A puppyPayload -> "(A " <> show puppyPayload <> ")"
    B puppyPayload -> "(B " <> show puppyPayload <> ")"

terminalIndex :: Puppy.Deps.Maybe Token -> Int
terminalIndex = case _ of
  Puppy.Deps.Just COMMA -> 0
  Puppy.Deps.Just (A _) -> 1
  Puppy.Deps.Just (B _) -> 2
  Puppy.Deps.Nothing -> 3

terminalValue :: Puppy.Deps.Maybe Token -> Puppy.Runtime.Value
terminalValue = case _ of
  Puppy.Deps.Just COMMA -> Puppy.Runtime.box unit
  Puppy.Deps.Just (A puppyPayload) -> Puppy.Runtime.box puppyPayload
  Puppy.Deps.Just (B puppyPayload) -> Puppy.Runtime.box puppyPayload
  Puppy.Deps.Nothing -> Puppy.Runtime.box unit

terminalNames :: Array String
terminalNames =
  [ "COMMA"
  , "A"
  , "B"
  , "end of input"
  ]

terminalName :: Int -> String
terminalName puppyIndex = case Puppy.Deps.index terminalNames puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no name for terminal " <> show puppyIndex)

productionTable :: Array Puppy.Runtime.ProductionInfo
productionTable =
  [ { lhs: 0, arity: 1, name: "items -> list" }
  , { lhs: 1, arity: 0, name: "list -> <empty>" }
  , { lhs: 1, arity: 2, name: "list -> item tail" }
  , { lhs: 2, arity: 1, name: "item -> A" }
  , { lhs: 2, arity: 1, name: "item -> B" }
  , { lhs: 3, arity: 0, name: "tail -> <empty>" }
  , { lhs: 3, arity: 3, name: "tail -> COMMA item tail" }
  , { lhs: 4, arity: 1, name: "single -> item" }
  , { lhs: 5, arity: 1, name: "<start items> -> items" }
  , { lhs: 6, arity: 1, name: "<start single> -> single" }
  ]

productionAt :: Int -> Puppy.Runtime.ProductionInfo
productionAt puppyIndex = case Puppy.Deps.index productionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no production " <> show puppyIndex)

semanticActionTable :: Array (Array Puppy.Runtime.Value -> Puppy.Runtime.Value)
semanticActionTable =
  [ \puppyValues ->
      let
        xs :: Array String
        xs = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((xs) :: Array String)
  , \_ ->
      Puppy.Runtime.box
        (([]) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)

        rest :: Array String
        rest = Puppy.Runtime.unbox (Puppy.Runtime.slot 1 puppyValues)
      in
        Puppy.Runtime.box
          (([ x ] <> rest) :: Array String)
  , \puppyValues ->
      let
        x = Puppy.Runtime.unbox (puppyInline3_0 puppyValues)
      in
        Puppy.Runtime.box
          (("[" <> x <> "]") :: String)
  , \puppyValues ->
      let
        x = Puppy.Runtime.unbox (puppyInline4_0 puppyValues)
      in
        Puppy.Runtime.box
          (("[" <> x <> "]") :: String)
  , \_ ->
      Puppy.Runtime.box
        (([]) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Puppy.Runtime.unbox (Puppy.Runtime.slot 1 puppyValues)

        rest :: Array String
        rest = Puppy.Runtime.unbox (Puppy.Runtime.slot 2 puppyValues)
      in
        Puppy.Runtime.box
          (([ x ] <> rest) :: Array String)
  , \puppyValues ->
      let
        x :: String
        x = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
      in
        Puppy.Runtime.box
          ((x) :: String)
  , \_ -> Puppy.Runtime.internalError
      "the start production has no semantic action"
  , \_ -> Puppy.Runtime.internalError
      "the start production has no semantic action"
  ]

semanticActionAt :: Int -> Array Puppy.Runtime.Value -> Puppy.Runtime.Value
semanticActionAt puppyIndex = case Puppy.Deps.index semanticActionTable puppyIndex of
  Puppy.Deps.Just puppyFound -> puppyFound
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no semantic action " <> show puppyIndex)

puppyInline3_0 :: Array Puppy.Runtime.Value -> Puppy.Runtime.Value
puppyInline3_0 puppyValues =
  let
    x :: String
    x = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
  in
    Puppy.Runtime.box
      (x <> "!")

puppyInline4_0 :: Array Puppy.Runtime.Value -> Puppy.Runtime.Value
puppyInline4_0 puppyValues =
  let
    x :: String
    x = Puppy.Runtime.unbox (Puppy.Runtime.slot 0 puppyValues)
  in
    Puppy.Runtime.box
      (x <> "?")

actionRows :: Array (Array { on :: Int, take :: Puppy.Runtime.Action })
actionRows =
  [ [ { on: 1, take: Puppy.Runtime.Shift 2 }, { on: 2, take: Puppy.Runtime.Shift 3 }, { on: 3, take: Puppy.Runtime.Reduce 1 } ]
  , [ { on: 1, take: Puppy.Runtime.Shift 2 }, { on: 2, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 0, take: Puppy.Runtime.Reduce 3 }, { on: 3, take: Puppy.Runtime.Reduce 3 } ]
  , [ { on: 0, take: Puppy.Runtime.Reduce 4 }, { on: 3, take: Puppy.Runtime.Reduce 4 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 7 } ]
  , [ { on: 3, take: Puppy.Runtime.Accept } ]
  , [ { on: 3, take: Puppy.Runtime.Accept } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 0 } ]
  , [ { on: 0, take: Puppy.Runtime.Shift 9 }, { on: 3, take: Puppy.Runtime.Reduce 5 } ]
  , [ { on: 1, take: Puppy.Runtime.Shift 2 }, { on: 2, take: Puppy.Runtime.Shift 3 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 2 } ]
  , [ { on: 0, take: Puppy.Runtime.Shift 9 }, { on: 3, take: Puppy.Runtime.Reduce 5 } ]
  , [ { on: 3, take: Puppy.Runtime.Reduce 6 } ]
  ]

actionAt :: Int -> Int -> Puppy.Runtime.Action
actionAt puppyState puppyTerminal = case Puppy.Deps.index actionRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no action row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyTerminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.take
    Puppy.Deps.Nothing -> Puppy.Runtime.Error

gotoRows :: Array (Array { on :: Int, to :: Int })
gotoRows =
  [ [ { on: 0, to: 6 }, { on: 1, to: 7 }, { on: 2, to: 8 } ]
  , [ { on: 2, to: 4 }, { on: 4, to: 5 } ]
  , []
  , []
  , []
  , []
  , []
  , []
  , [ { on: 3, to: 10 } ]
  , [ { on: 2, to: 11 } ]
  , []
  , [ { on: 3, to: 12 } ]
  , []
  ]

gotoAt :: Int -> Int -> Int
gotoAt puppyState puppyNonterminal = case Puppy.Deps.index gotoRows puppyState of
  Puppy.Deps.Nothing -> Puppy.Runtime.internalError
    ("no goto row for state " <> show puppyState)
  Puppy.Deps.Just puppyRow -> case Puppy.Deps.find (\puppyEntry -> puppyEntry.on == puppyNonterminal) puppyRow of
    Puppy.Deps.Just puppyEntry -> puppyEntry.to
    Puppy.Deps.Nothing -> Puppy.Runtime.internalError
      ("no goto from state " <> show puppyState <> " on " <> show puppyNonterminal)

tableFor :: Int -> Puppy.Runtime.Table (Puppy.Deps.Maybe Token) Puppy.Runtime.Value
tableFor puppyStart =
  { action: actionAt
  , goto: gotoAt
  , production: productionAt
  , semanticAction: semanticActionAt
  , terminalIndex
  , terminalValue
  , terminalName
  , terminalCount: 4
  , startState: puppyStart
  }

-- | End of input is `Puppy.Deps.Nothing` to the driver and nothing at all to a
-- | caller, so an error that landed on it reports no token rather than one the
-- | caller has no way to name.
toParseError
  :: Puppy.Runtime.ParseError (Puppy.Deps.Maybe Token)
  -> Puppy.Runtime.ParseError Token
toParseError puppyError =
  puppyError { found = Puppy.Deps.fromMaybe Puppy.Deps.Nothing puppyError.found }

fromResult
  :: forall puppyResult
   . Puppy.Deps.Either (Puppy.Runtime.ParseError (Puppy.Deps.Maybe Token)) Puppy.Runtime.Value
  -> Puppy.Deps.Either (Puppy.Runtime.ParseError Token) puppyResult
fromResult = case _ of
  Puppy.Deps.Left puppyError -> Puppy.Deps.Left (toParseError puppyError)
  Puppy.Deps.Right puppyValue -> Puppy.Deps.Right (Puppy.Runtime.unbox puppyValue)

-- | Feed the parser from an array, without building a second one.
-- |
-- | The driver's token here is `Puppy.Deps.Maybe Token`, and that is exactly
-- | what a lookup past the end of an array answers, so the same
-- | `Puppy.Deps.index` both reads a token and says there are no more.
runArray
  :: Array Token
  -> Int
  -> Puppy.Runtime.Step (Puppy.Deps.Maybe Token) Puppy.Runtime.Value
  -> Puppy.Deps.Either (Puppy.Runtime.ParseError (Puppy.Deps.Maybe Token)) Puppy.Runtime.Value
runArray puppyInput puppyIndex puppyStep = case puppyStep of
  Puppy.Runtime.Await puppyResume ->
    runArray puppyInput (puppyIndex + 1)
      (Puppy.Runtime.resume puppyResume (Puppy.Deps.index puppyInput puppyIndex))
  Puppy.Runtime.Done puppyValue -> Puppy.Deps.Right puppyValue
  Puppy.Runtime.Failed puppyError -> Puppy.Deps.Left puppyError

items :: Array Token -> Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (Array String)
items puppyInput =
  fromResult (runArray puppyInput 0 (Puppy.Runtime.start (tableFor 0)))

itemsFrom
  :: forall m
   . Puppy.Deps.MonadRec m
  => m (Puppy.Deps.Maybe Token)
  -> m (Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (Array String))
itemsFrom puppyNext =
  map fromResult (Puppy.Runtime.parseM (tableFor 0) puppyNext)

single :: Array Token -> Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (String)
single puppyInput =
  fromResult (runArray puppyInput 0 (Puppy.Runtime.start (tableFor 1)))

singleFrom
  :: forall m
   . Puppy.Deps.MonadRec m
  => m (Puppy.Deps.Maybe Token)
  -> m (Puppy.Deps.Either (Puppy.Runtime.ParseError Token) (String))
singleFrom puppyNext =
  map fromResult (Puppy.Runtime.parseM (tableFor 1) puppyNext)
